# Generated by Django 2.1.7 on 2019-03-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('commission_type', models.CharField(choices=[('percent_of_deal', 'percent_of_deal'), ('no_commission', 'no_commission')], max_length=64)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.Currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='TransferFundsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], max_length=32)),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.ClientAccount')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.ClientAccount')),
                ('conversion_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.CurrencyConversionRate')),
            ],
        ),
        migrations.CreateModel(
            name='TransferFundsOrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_charged', models.DecimalField(decimal_places=2, max_digits=16)),
                ('commission_charged', models.DecimalField(decimal_places=2, max_digits=16)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.TransferFundsOrder')),
            ],
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Currency'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyconversionrate',
            unique_together={('currency_from', 'currency_to')},
        ),
    ]
