# Generated by Django 2.1.7 on 2019-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190312_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='commission_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
