# Generated by Django 2.1.7 on 2019-03-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190312_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfundsorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=32),
        ),
    ]
